### ISSUE TITLE
TexToGaussian.FileTypeToString does not exist

### ISSUE THREAD

**Issue by float3** [Error-mdl/UnityGaussianTex#1]
#https://github.com/Error-mdl/UnityGaussianTex/blob/master/GaussianTex/Editor/Scripts/GaussTexUI.cs#L166

broke in commit https://github.com/Error-mdl/UnityGaussianTex/commit/63dc3da405509ffecb9a14f58f7b9de1db218aa3#diff-929ce5fbd47b674468ee83d6a2f65387322bf46b4a001b8b9014621f8827d304

because TexToGaussian.FileTypeToString does not exist.

Also, I don't think any explicit conversion to string is neccessary.

**Comment by Error-mdl** [comment]
Somehow I managed to push the changes made to the UI script but not the actual converter class. The latest commit should include the missing method now.
