### ISSUE TITLE
Unity Warning Spam

### ISSUE THREAD

**Issue by float3** [Error-mdl/UnityGaussianTex#3]
Doing `break` after a `return` statement causes Unity to print Unreachable code warnings in the console 

![image](https://user-images.githubusercontent.com/86748455/142380233-190ceff3-ec9a-4314-8630-4a807da64afc.png)

```
public static string FileTypeToString(FileType fileT)
{
  switch (fileT)
  {
    case FileType.png:
      return ".png";
      break;
    case FileType.jpg:
      return ".jpg";
      break;
    case FileType.tga:
     return ".tga";
      break;
    case FileType.exr:
      return ".exr";
      break;
    default:
      return ".png";
      break;
  }
}
```

**Comment by Error-mdl** [comment]
I've removed the break statements, it shouldn't throw any errors now.
